const P={A:[1,12000,.3],B:[1,10000,.4],C:[1,12000,.3],D:[1,17000,.1],E:[2,15000,.2],F:[3,16000,.2]};
const M={1:[72000,35000,1800],2:[120000,95000,2900],3:[68000,38000],4:[95000,70000,2900],5:[45000,28000,1300],6:[110000,90000,2900]};
const $=x=>document.getElementById(x),R=x=>Math.round(x||0),N=x=>{x=String(x??"").replaceAll(",","").trim();return x===""?null:Number(x)},S=x=>`${x<0?"−":""}Sh ${Math.abs(R(x)).toLocaleString()}`;
let plans={A:{milk:"2",market:"1000",request:"40000",sales:"40000",loan:"0",term:"4",premise:"B",machine:"5",bought:"1",production:"40000"},B:{milk:"2",market:"1000",request:"40000",sales:"30000",loan:"0",term:"4",premise:"A",machine:"5",bought:"1",production:"40000"}};

function calc(x){
  let q=Object.fromEntries(Object.entries(x).map(([k,v])=>[k,["premise","machine"].includes(k)?v:(N(v)??0)]));
  let e=[],p=P[q.premise]||P.B,m=M[q.machine]||M[5];
  if(q.milk<1)e.push("Buy at least one ton of milk.");if(q.market<1000)e.push("Market investment must be at least Sh 1,000.");
  if(q.request&&q.request%10000)e.push("Sales requests must be zero or multiples of 10,000.");if(q.sales>q.request||q.sales>q.production)e.push("Allocated sales exceed request or production.");
  if(q.production>q.milk*20000)e.push("Production exceeds milk available.");if(q.production>m[0]*q.bought)e.push("Production exceeds machine capacity.");if(q.bought>p[0])e.push("Too many machines for this premise.");
  let rev=R(q.sales*2),milk=R(q.milk*20000),maint=R(m[2]*q.bought),depr=R(m[1]/8*q.bought),gross=R(rev-milk-maint-depr),transport=R(q.sales*p[2]),bonus=gross>0?R(gross*.05):0,interest=R(q.loan*.1),principal=q.loan?R(q.loan/Math.max(1,q.term)):0,pbt=R(gross-transport-q.market-bonus-10000-p[1]-interest),used=Math.min(q.openLoss,Math.max(0,pbt)),tax=R(Math.max(0,pbt-used)*.1),net=R(pbt-tax),loss=R(q.openLoss-used+(pbt<0?-pbt:0)),purchase=R(m[1]*q.bought),advance=R(q.cash+q.loan-purchase-milk-q.market),close=R(q.cash+q.loan+rev-purchase-milk-q.market-p[1]-maint-transport-10000-bonus-interest-principal-tax);
  return{...q,e,rev,milk,maint,depr,gross,transport,rent:p[1],bonus,interest,principal,pbt,used,tax,net,loss,purchase,advance,close,unused:R(q.milk*20000-q.production),unsold:R(q.production-q.sales)};
}
function tr(a,b,bold=false){return`<tr${bold?" class='good'":""}><td>${a}</td><td>${S(b)}</td></tr>`}
function show(r){
  return `${r.e.map(x=>`<div class="warning">${x}</div>`).join("")}<table>${tr("Revenue",r.rev)}${tr("Milk cost",-r.milk)}${tr("Maintenance",-r.maint)}${tr("Depreciation",-r.depr)}${tr("Gross profit",r.gross,true)}${tr("Transport",-r.transport)}${tr("Market investment",-r.market)}${tr("Bonus",-r.bonus)}${tr("Salaries",-10000)}${tr("Rent",-r.rent)}${tr("Loan interest",-r.interest)}${tr("Profit before tax",r.pbt,true)}${tr("Tax losses used",-r.used)}${tr("Game tax",-r.tax)}${tr("Net profit / loss",r.net,true)}${tr("Closing cash",r.close,true)}</table><p class="${r.advance<0||r.close<0?"bad":"good"}">Advance cash: ${S(r.advance)} · Closing cash: ${S(r.close)}</p><p>Unused milk: ${r.unused.toLocaleString()} units equivalent. Unsold ice cream: ${r.unsold.toLocaleString()} units. Closing tax-loss pool: ${S(r.loss)}.</p>`}
function planForm(id){
  let x=plans[id],prem=Object.keys(P).map(v=>`<option ${v===x.premise?"selected":""}>${v}</option>`).join(""),mac=Object.keys(M).map(v=>`<option ${v===x.machine?"selected":""}>${v}</option>`).join("");
  return `<div class="form two">${["milk|Milk tons","market|Market investment, Sh","request|Sales request, units","sales|Allocated sales, units","loan|New loan, Sh","term|Repayment term"].map(z=>{let[k,l]=z.split("|");return`<label>${l}<input data-p="${id}" data-k="${k}" value="${x[k]}"></label>`}).join("")}<label>Premise<select data-p="${id}" data-k="premise">${prem}</select></label><label>Machine<select data-p="${id}" data-k="machine">${mac}</select></label><label>Machine copies bought<input data-p="${id}" data-k="bought" value="${x.bought}"></label><label>Production, units<input data-p="${id}" data-k="production" value="${x.production}"></label></div>`
}
function render(){
  ["A","B"].forEach(id=>{$(`${id.toLowerCase()}Inputs`).innerHTML=planForm(id);$(`${id.toLowerCase()}Output`).innerHTML=show(calc({...plans[id],cash:$("rollCash").value,openLoss:$("rollLoss").value}))});
  document.querySelectorAll("[data-p]").forEach(el=>el.oninput=e=>{plans[e.target.dataset.p][e.target.dataset.k]=e.target.value;let id=e.target.dataset.p;$(`${id.toLowerCase()}Output`).innerHTML=show(calc({...plans[id],cash:$("rollCash").value,openLoss:$("rollLoss").value}));compare()});compare();
}
function compare(){let a=calc({...plans.A,cash:$("rollCash").value,openLoss:$("rollLoss").value}),b=calc({...plans.B,cash:$("rollCash").value,openLoss:$("rollLoss").value});$("compare").innerHTML=`<table><tr><th>Metric</th><th>Option A</th><th>Option B</th></tr>${["rev|Revenue","gross|Gross profit","transport|Transport","rent|Rent","purchase|Machine purchases","net|Net profit / loss","advance|Advance cash","close|Closing cash"].map(z=>{let[k,l]=z.split("|");return`<tr><td>${l}</td><td>${S(a[k])}</td><td>${S(b[k])}</td></tr>`}).join("")}</table><p>${a.close>b.close?"Option A":b.close>a.close?"Option B":"Neither option"} has higher projected closing cash. Lower sales reduce revenue by Sh 2 per unit but do not reduce committed costs.</p>`}
function verify(){let r=calc({cash:$("cash").value,openLoss:$("loss").value,milk:$("milk").value,market:$("market").value,request:$("request").value,sales:$("sales").value,loan:0,term:4,premise:$("premise").value,machine:$("machine").value,bought:$("bought").value,production:$("production").value}),p=N($("expectedProfit").value),c=N($("expectedCash").value);$("verifyOutput").innerHTML=`<p>Gross profit: <b>${S(r.gross)}</b> · Bonus: <b>${S(r.bonus)}</b></p><p class="${r.net===p?"good":"bad"}">Net profit: ${S(r.net)} — ${r.net===p?"PASS":"FAIL"}</p><p class="${r.close===c?"good":"bad"}">Closing cash: ${S(r.close)} — ${r.close===c?"PASS":"FAIL"}</p><p class="${r.loss===3560?"good":"bad"}">Closing tax-loss pool: ${S(r.loss)}</p>`}
$("example").onclick=()=>{["cash","loss","milk","market","request","sales","bought","production"].forEach((k,i)=>$(k).value=[100000,0,2,1000,40000,40000,1,40000][i]);$("premise").value="B";$("machine").value="5";verify()};
$("check").onclick=verify;$("tests").onclick=()=>{let r=calc({cash:100000,openLoss:0,milk:2,market:1000,request:40000,sales:40000,loan:0,term:4,premise:"B",machine:"5",bought:1,production:40000});$("testOutput").innerHTML=[["Worked example",r.gross===35200&&r.net===-3560&&r.close===71940&&r.loss===3560],["Transport allocation",R(42000*.3)+R(28000*.4)===23800],["Idle maintenance",M[5][2]===1300],["Depreciation",R(M[5][1]/8)===3500],["Loan interest",R(60000*.1)===6000],["Tax loss offset",Math.min(50000,100000)===50000],["Advance warning",calc({...r,milk:10}).advance<0],["Zero sales cost",calc({...r,request:0,sales:0}).milk>=20000],["Whole-shekel rounding",Number.isInteger(r.transport)],["No NaN",!Object.values(r).some(Number.isNaN)]].map(x=>`<p class="${x[1]?"good":"bad"}">${x[1]?"PASS":"FAIL"} — ${x[0]}</p>`).join("")};
["rollCash","rollLoss"].forEach(id=>$(id).oninput=render);render();verify();
